var ApiConstants = {
  ALL_BUSINESSES: "ALL_BUSINESSES",
  ABRIDGED_BUSINESSES: "ABRIDGED_BUSINESSES",
  SINGLE_BUINESS: "SINGLE_BUINESS",
  ALL_BUSINESS_ERRORS: "ALL_BUSINESS_ERRORS",
  ALL_REVIEWS: "ALL_REVIEWS",
  SINGLE_REVIEW: "SINGLE_REVIEW",
  ALL_REVIEW_ERRORS: "ALL_REVIEW_ERRORS",
  ALL_TAGS: "ALL_TAGS",
  SEARCH_SUGGESTIONS: "SEARCH_SUGGESTIONS",
  QUERY_STRING: "QUERY_STRING"
};

module.exports = ApiConstants;
