var ApiConstants = {
  ALL_BUSINESSES: "ALL_BUSINESSES",
  ALL_BUSINESS_ERRORS: "ALL_BUSINESS_ERRORS",
  ALL_REVIEWS: "ALL_REVIEWS",
  ALL_REVIEW_ERRORS: "ALL_REVIEW_ERRORS"
};

module.exports = ApiConstants;
