var FilterConstants = {
  UPDATE_BOUNDS: "UPDATE_BOUNDS",
  UPDATE_TAGS: "UPDATE_TAGS",
  UPDATE_ATTRIBUTES: "UPDATE_ATTRIBUTES",
  UPDATE_PRICE: "UPDATE_PRICE",
  UPDATE_RATING: "UPDATE_RATING",
  UPDATE_NUM_REVIEWS: "UPDATE_NUM_REVIEWS"
};

module.exports = FilterConstants;
